[tool.black]
line-length = 100
exclude = '''
/(
    environments
    | archived_environments
    | \.git
    | \.venv
    | __pycache__
)/
'''

[tool.isort]
profile = "black"
skip = ["environments", "archived_environments"]

[tool.pylint]
ignore = ["environments", "archived_environments"]
disable = [
    "line-too-long",
    "missing-module-docstring",
    "missing-function-docstring"
]
